name: Node.js CI

on: [push]  # どのブランチでも、pushされたら実行する

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # GitHubが用意したUbuntu仮想マシンを使う

    steps:
    - name: ソースコードのチェックアウト
      uses: actions/checkout@v3

    - name: Node.jsのセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    
    - name: workspace の中身確認
      run: |
        echo "=== PWD ==="
        pwd
        echo "=== LS ==="
        ls -la
        echo "=== Find files (maxdepth 3) ==="
        find . -maxdepth 3 -type f -print
        echo "=== Current commit ==="
        git rev-parse HEAD || true
        echo "=== Branch ==="
        git branch -a || true


    - name: ライブラリのインストール
      run: npm install

    - name: 構文チェック (Lint)
      run: npm run lint

    - name: 単体テスト (Test)
      run: npm run test
